/**
 * Run storage for the web app: one JSON file per research run in a data
 * directory. Phase 0 deliberately has no database; a run is small and
 * written a handful of times.
 */

import type { BallotCandidate, RaceDossier, RaceQuery } from "../types.ts";

export type RunStatus = "queued" | "running" | "done" | "failed" | "interrupted";

export interface RunRecord {
  id: string;
  query: RaceQuery;
  /** Candidate list the user supplied, if any; null means ballot discovery. */
  candidates: BallotCandidate[] | null;
  status: RunStatus;
  created_at: string;
  updated_at: string;
  error: string | null;
  /** Partial while running, complete when done; null until the ballot is known. */
  race: RaceDossier | null;
}

/** Ids are generated by the app; anything else is refused before it touches the filesystem. */
const ID_RE = /^[a-z0-9][a-z0-9-]{0,119}$/;

export function isRunId(id: string): boolean {
  return ID_RE.test(id);
}

export class RunStore {
  constructor(readonly dir: string) {}

  #path(id: string): string {
    if (!isRunId(id)) throw new Error(`invalid run id: ${id}`);
    return `${this.dir}/${id}.json`;
  }

  async init(): Promise<void> {
    await Deno.mkdir(this.dir, { recursive: true });
  }

  /** Atomic save: write a temp file, then rename over the old one. */
  async save(run: RunRecord): Promise<void> {
    const path = this.#path(run.id);
    const tmp = `${path}.${crypto.randomUUID()}.tmp`;
    await Deno.writeTextFile(tmp, JSON.stringify(run));
    await Deno.rename(tmp, path);
  }

  async get(id: string): Promise<RunRecord | null> {
    if (!isRunId(id)) return null;
    try {
      return JSON.parse(await Deno.readTextFile(this.#path(id))) as RunRecord;
    } catch (err) {
      if (err instanceof Deno.errors.NotFound || err instanceof SyntaxError) return null;
      throw err;
    }
  }

  /** All runs, newest first. Unreadable files are skipped, not fatal. */
  async list(): Promise<RunRecord[]> {
    const runs: RunRecord[] = [];
    try {
      for await (const e of Deno.readDir(this.dir)) {
        if (!e.isFile || !e.name.endsWith(".json")) continue;
        const run = await this.get(e.name.slice(0, -5));
        if (run) runs.push(run);
      }
    } catch (err) {
      if (!(err instanceof Deno.errors.NotFound)) throw err;
    }
    return runs.sort((a, b) => b.created_at.localeCompare(a.created_at));
  }

  /**
   * A run that was queued or running when the server stopped will never
   * finish. Say so rather than leaving it spinning forever.
   */
  async markInterrupted(now: string): Promise<number> {
    let n = 0;
    for (const run of await this.list()) {
      if (run.status !== "queued" && run.status !== "running") continue;
      await this.save({
        ...run,
        status: "interrupted",
        updated_at: now,
        error: "The server restarted before this research finished.",
      });
      n++;
    }
    return n;
  }
}
